Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Models/ErrorViewModel.cs
using System;

namespace DropdownListWithDatabase.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DropdownListWithDatabase.Models
{
	public class Person
	{
		public int Id { get; set; }
		[Required]
		[Display(Name = "Имя")]
		public string FirstName { get; set; }
		[Required]
		[Display(Name = "Фамилия")]
		public string LastName { get; set; }
		[Display(Name = "Отчество")]
		public string MiddleName { get; set; }
		[Required]
		[Display(Name = "Серия паспорта")]
		public string PassportSeries { get; set; }
		[Required]
		[Display(Name = "Номер паспорта")]
		public string PassportSerialNumber { get; set; }
	}
}

Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Controllers/Api/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using DropdownListWithDatabase.Data;
using DropdownListWithDatabase.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DropdownListWithDatabase.Controllers.Api
{
    [ApiController]
    [Route("api/[controller]")]
    public class PersonController : ControllerBase
    {
        private readonly IPersonRepository personRepository;

        public PersonController(IPersonRepository personRepository)
        {
            this.personRepository = personRepository;
        }

        [HttpGet()]
        public IActionResult GetByPassportSerialNumber (string serialNumber)
        {
            var persons = personRepository.GetPersonsByPassportSerialNumber(serialNumber);
            return new ObjectResult(persons);
        }
    }
}

Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Controllers/DropdownListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DropdownListWithDatabase.Data;
using Microsoft.AspNetCore.Mvc;

namespace DropdownListWithDatabase.Controllers
{
    public class DropdownListController : Controller
    {
        private readonly IPersonRepository personRepository;

        public DropdownListController(IPersonRepository personRepository)
        {
            this.personRepository = personRepository;
        }

        public IActionResult Index()
        {
            return View(personRepository.Get());
        }

        public IActionResult Result (int id)
        {
            DropdownResultVM vm = new DropdownResultVM();

            var person = personRepository.Get(id);
            if (person != null)
            {
                vm.Person = person;
                vm.Message = "Успех. Данные успешно отправлены.";
            }
            else
            {
                vm.Message = "Данные не были отправлены. Произошла ошибка. Пользователь не был выбран.";
            }

            return View(vm);
        }
    }
}

Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DropdownListWithDatabase.Models;

namespace DropdownListWithDatabase.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DropdownListWithDatabase.Data;
using DropdownListWithDatabase.Models;
using Microsoft.AspNetCore.Mvc;

namespace DropdownListWithDatabase.Controllers
{
	public class PersonsController : Controller
	{
		private readonly IPersonRepository personRepository;

		private const string PersonForm = "PersonForm";

		public PersonsController(IPersonRepository personRepository)
		{
			this.personRepository = personRepository;
		}

		public IActionResult Index()
		{
			return View(personRepository.Get());
		}

		public IActionResult Create()
		{
			return View(PersonForm, new Person());
		}

		public IActionResult Edit(int id)
		{
			return View(PersonForm, personRepository.Get(id));
		}

		public IActionResult Details(int id)
		{
			return View(personRepository.Get(id));
		}

		public IActionResult Save(Person person)
		{
			if (!ModelState.IsValid)
				return View(person);

			if (person.Id == 0)
				personRepository.Add(person);
			else personRepository.Update(person.Id, person);
			personRepository.SaveChanges();

			return RedirectToAction(nameof(Index));
		}

		public IActionResult Delete(int id)
		{
			personRepository.Delete(id);
			personRepository.SaveChanges();

			return RedirectToAction(nameof(Index));
		}
	}
}

Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Views/DropdownList/Index.cshtml
@model IEnumerable<Person>

@{
	ViewData["Title"] = "Dropdown List Example";
}

<h1 class="mb-5">Выпадающий список : Поиск по базе данных</h1>

@if (Model != null && Model.Any())
{
	<form asp-action="Result" class="col-md-12">
		<div class="row mx-auto">
			<div class="form-group col-md-4">
				<input id="search" class="form-control" placeholder="Введите номер паспорта" />
			</div>
			<div class="form-group col-md-8">
				<select id="list" asp-items="@(new SelectList(Model, "Id", "FirstName"))" name="id" class="custom-select">
					<option value="" selected>-- Выберите один --</option>
				</select>
			</div>
			<div class="form-group col-md-12">
				<input type="submit" value="Отправить" class="btn btn-primary btn-block" />
			</div>
		</div>
	</form>
}
else
{
	<h3 class="text-danger">No Items in the Database</h3>
}

@section Scripts {

	<script>
		$(document).ready(function () {
			$("#search").on("change", function () {
				$list = $("#list");
				$.ajax({
					url: "api/Person",
					type: "GET",
					data: { serialNumber: $("#search").val() }, //id of the state which is used to extract cities
					traditional: true,
					success: function (result) {
						$list.empty();
						$.each(result, function (i, item) {
							$list.append('<option value="' + item["id"] + '"> ' + item["firstName"] + ' </option>');
						});
					},
					error: function () {
						alert("Something went wrong call the police");
					}
				});
			});
		});
	</script>

}

Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Views/DropdownList/Result.cshtml
@model DropdownListWithDatabase.Data.DropdownResultVM

@{
	ViewData["Title"] = "Result";
}

@if (Model.Person != null)
{
	<h2 class="text-success">@Model.Message</h2>
	<div>
		<h4>Налогоплательщик</h4>
		<hr />
		<dl class="row">
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Person.FirstName)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Person.FirstName)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Person.LastName)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Person.LastName)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Person.MiddleName)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Person.MiddleName)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Person.PassportSeries)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Person.PassportSeries)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Person.PassportSerialNumber)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Person.PassportSerialNumber)
			</dd>
		</dl>
	</div>
}
else
{
	<h2 class="text-danger">@Model.Message</h2>
}

Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}

<div class="text-center">
	<h1 class="display-4 mb-4">Добро Пожаловать</h1>
	<div class="col-md-5 mx-auto mb-5 text-left">
		<h4>Проект - Выпадающий список</h4>
		<p class="mb-2">Выполнил: Дегтярёв Валерий</p>
		<p>Группа: 3ПИ</p>
	</div>
	<a asp-controller="DropdownList" asp-action="Index" class="btn btn-primary">Пример</a>
</div>

Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Views/Persons/Details.cshtml
@model DropdownListWithDatabase.Models.Person

@{
    ViewData["Title"] = $"{@Model.FirstName} {@Model.LastName} - Details";
}

<h1>Details</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassportSeries)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassportSeries)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassportSerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassportSerialNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a> |
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Views/Persons/Index.cshtml
@model IEnumerable<DropdownListWithDatabase.Models.Person>

@{
	ViewData["Title"] = "Persons List";
}

<h1 class="text-center">Налогоплательщики</h1>

<p>
	<a asp-action="Create" class="btn btn-primary">Create New</a>
</p>

<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.FirstName)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.LastName)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.MiddleName)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.PassportSeries)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.PassportSerialNumber)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@if (Model.Any())
		{
			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.FirstName)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.LastName)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.MiddleName)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.PassportSeries)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.PassportSerialNumber)
					</td>
					<td>
						<a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Edit</a>
						<a asp-action="Details" asp-route-id="@item.Id"class="btn btn-primary">Details</a>
						<a asp-action="Delete" asp-route-id="@item.Id"class="btn btn-danger">Delete</a>
					</td>
				</tr>
			}
		}
		else
		{
			<h3 class="text-danger">No Items in the Database</h3>
		}
	</tbody>
</table>

Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Views/Persons/PersonForm.cshtml
@model DropdownListWithDatabase.Models.Person

@{
	ViewData["Title"] = "PersonForm";
}

<h1 class="text-center">Person Form</h1>

@if (Model.Id == 0)
{
	<h4>Create Person</h4>
}
else
{
	<h4>Edit: @Model.FirstName @Model.LastName : @Model.PassportSeries : @Model.PassportSerialNumber</h4>
}

<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Save">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id" />
			<div class="form-group">
				<label asp-for="FirstName" class="control-label"></label>
				<input asp-for="FirstName" class="form-control" />
				<span asp-validation-for="FirstName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="LastName" class="control-label"></label>
				<input asp-for="LastName" class="form-control" />
				<span asp-validation-for="LastName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="MiddleName" class="control-label"></label>
				<input asp-for="MiddleName" class="form-control" />
				<span asp-validation-for="MiddleName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="PassportSeries" class="control-label"></label>
				<input asp-for="PassportSeries" class="form-control" />
				<span asp-validation-for="PassportSeries" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="PassportSerialNumber" class="control-label"></label>
				<input asp-for="PassportSerialNumber" class="form-control" />
				<span asp-validation-for="PassportSerialNumber" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Practice work 8 - SelectList From Database/DropdownList/DropdownListWithDatabase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - DropdownListWithDatabase</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DropdownList</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav ">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Persons" asp-action="Index">Persons</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="DropdownList" asp-action="Index">Dropdown List Example</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2020 - DropdownListWithDatabase - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>