Practice work 7 - Calculator/LeoDeg.Calculator/Calculator/Models/CalculationInfoDTO.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Calculator.Models
{
	public class CalculationInfoDTO
	{
		[Required]
		[Display(Name = "Первое значение")]
		public int X { get; set; }

		[Required]
		[Display(Name = "Второе значение")]
		public int Y { get; set; }

		[Required]
		[Display(Name = "Операция")]
		public CalculatorMachine.Operation Operation { get; set; }

		public int Result { get; set; }
		public string ErrorMessage { get; set; }
	}
}

Practice work 7 - Calculator/LeoDeg.Calculator/Calculator/Models/CalculatorMachine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Calculator.Models
{
	public class CalculatorMachine
	{
		public enum Operation
		{
			[Display(Name = "+")]
			Add,
			[Display(Name = "-")]
			Substract,
			[Display(Name = "*")]
			Multiply,
			[Display(Name = "/")]
			Divide,
			[Display(Name = "mod")]
			Mod
		}

		public Dictionary<Operation, Func<int, int, int>> Expressions = new Dictionary<Operation, Func<int, int, int>>
		{
			{ Operation.Add, (x, y) => x + y },
			{ Operation.Substract, (x, y) => x - y },
			{ Operation.Multiply, (x, y) => x * y },
			{ Operation.Divide, (x, y) => x / y },
			{ Operation.Mod, (x, y) => x % y },
		};

		public int Calculate(int x, int y, Operation operation)
		{
			Func<int, int, int> expression;
			Expressions.TryGetValue(operation, out expression);
			return expression.Invoke(x, y);
		}
	}
}

Practice work 7 - Calculator/LeoDeg.Calculator/Calculator/Models/ErrorViewModel.cs
using System;

namespace Calculator.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Practice work 7 - Calculator/LeoDeg.Calculator/Calculator/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Calculator.Models;
using Microsoft.AspNetCore.Mvc;

namespace Calculator.Controllers
{
	public class CalculatorController : Controller
	{
		private readonly CalculatorMachine calculator;

		public CalculatorController(CalculatorMachine calculator)
		{
			this.calculator = calculator;
		}

		public IActionResult Index(CalculationInfoDTO information)
		{
			return View(information ?? new CalculationInfoDTO());
		}

		public IActionResult Calculate(CalculationInfoDTO information)
		{
			if (!ModelState.IsValid)
			{
				return RedirectToAction(nameof(Index), information);
			}

			try
			{
				information.Result = calculator.Calculate(
					information.X,
					information.Y,
					information.Operation
				);
			}
			catch (DivideByZeroException)
			{
				information.Result = 0;
				information.ErrorMessage = "Вы не можете делить на нуль!";
			}

			return RedirectToAction(nameof(Index), information);
		}
	}
}

Practice work 7 - Calculator/LeoDeg.Calculator/Calculator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Calculator.Models;

namespace Calculator.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Practice work 7 - Calculator/LeoDeg.Calculator/Calculator/Views/Calculator/Index.cshtml
@model CalculationInfoDTO

@{
	ViewData["Title"] = "Index";
}

<h1>Калькулятор</h1>

<div class="row">
	<div class="col-md-4">
		<form asp-action="Calculate">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="X" class="control-label"></label>
				<input asp-for="X" class="form-control" />
				<span asp-validation-for="X" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Y" class="control-label"></label>
				<input asp-for="Y" class="form-control" />
				<span asp-validation-for="Y" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="Operation" class="control-label"></label>
				<select asp-for="Operation"
						asp-items="Html.GetEnumSelectList<CalculatorMachine.Operation>()"
						class="form-control">
				</select>
				<span asp-validation-for="Operation" class="text-danger"></span>
			</div>

			<div class="form-group">
				<input type="submit" value="Посчитать" class="btn btn-primary" />
			</div>
		</form>

		<h3>Результат</h3>
		@if (Model.ErrorMessage != null && Model.ErrorMessage.Length > 0)
		{
			<p class="text-danger font-weight-bold">@Model.ErrorMessage</p>
		}
		else
		{
			<p class="text-success font-weight-bold">@Model.Result</p>
		}

	</div>
</div>

Practice work 7 - Calculator/LeoDeg.Calculator/Calculator/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h2>Проект - Калькулятор</h2>
    <p>Выполнил: Дегтярёв Валерий</p>
    <p>Группа: 3ПИ</p>
	<a asp-controller="Calculator" asp-action="Index" class="btn btn-primary">Калькулятор</a>
</div>

Practice work 7 - Calculator/LeoDeg.Calculator/Calculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Calculator</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Index">Calculator</a>
						</li>
					</ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Calculator
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>